/**
 * MCP Forge — Auth Generator
 *
 * Generates authentication module code based on detected auth strategy.
 * Supports: API Key, Bearer, OAuth2, SSO Browser, Basic, HAR Capture.
 */

import type { ApiSpec, AuthStrategy, TokenConfig } from '../types/index.js';

/**
 * Generate multi-token helper when spec has tokenConfigs.
 * Each service can request a specific token type.
 * Learned from MS365: Teams, Outlook, SharePoint each need different tokens.
 */
export function generateMultiTokenHelper(tokens: TokenConfig[]): string {
  const tokenEntries = tokens.map(t => `
  '${t.type}': {
    name: '${t.name}',
    captureUrl: ${t.captureUrl ? `'${t.captureUrl}'` : 'undefined'},
    ttlMs: ${t.ttlMs || 3600000},
    scopes: ${JSON.stringify(t.scopes || [])},
  },`).join('');

  return `
// ─── Multi-Token Support (for complex platforms with multiple APIs) ──

interface TokenEntry { token: string; expiresAt: number; }
const tokenCache = new Map<string, TokenEntry>();

const TOKEN_CONFIGS: Record<string, { name: string; captureUrl?: string; ttlMs: number; scopes: string[] }> = {${tokenEntries}
};

export function getToken(type: string = 'primary'): string | null {
  const cached = tokenCache.get(type);
  if (cached && cached.expiresAt > Date.now() + 60_000) {
    return cached.token;
  }

  const config = TOKEN_CONFIGS[type];
  if (!config) return getValidToken(); // fallback to primary

  // Try keychain first
  const keychainToken = keychainGet(config.name + '-token');
  if (keychainToken) {
    tokenCache.set(type, { token: keychainToken, expiresAt: Date.now() + config.ttlMs });
    return keychainToken;
  }

  // Fallback to primary token
  return getValidToken();
}

export function setToken(type: string, token: string, ttlMs?: number): void {
  const config = TOKEN_CONFIGS[type];
  const ttl = ttlMs || config?.ttlMs || 3600000;
  tokenCache.set(type, { token, expiresAt: Date.now() + ttl });
  keychainSet(config?.name + '-token' || type, token);
}
`;
}

export function generateAuthModule(spec: ApiSpec): string {
  const prefix = spec.title.toUpperCase().replace(/[^A-Z0-9]/g, '_');
  const strategy = spec.authStrategy;

  return `/**
 * Authentication Module — Auto-generated by MCP Forge
 * Strategy: ${strategy}
 */

import { execSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

const SERVICE_NAME = '${spec.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-mcp';
const CACHE_DIR = join(homedir(), '.mcp-forge', SERVICE_NAME);

// ─── macOS Keychain Integration ──────────────────────────────

function keychainGet(account: string): string | null {
  try {
    const result = execSync(
      \`security find-generic-password -s "\${SERVICE_NAME}" -a "\${account}" -w 2>/dev/null\`,
      { encoding: 'utf-8' }
    ).trim();
    return result || null;
  } catch {
    return null;
  }
}

function keychainSet(account: string, password: string): void {
  try {
    // Delete existing entry first (ignore errors)
    try {
      execSync(\`security delete-generic-password -s "\${SERVICE_NAME}" -a "\${account}" 2>/dev/null\`);
    } catch { /* ignore */ }
    execSync(
      \`security add-generic-password -s "\${SERVICE_NAME}" -a "\${account}" -w "\${password.replace(/"/g, '\\\\"')}"\`
    );
  } catch (err) {
    console.error(\`[auth] Failed to save to Keychain: \${err}\`);
    // Fallback to encrypted file cache
    ensureCacheDir();
    writeFileSync(join(CACHE_DIR, \`\${account}.enc\`), password);
  }
}

function ensureCacheDir(): void {
  if (!existsSync(CACHE_DIR)) mkdirSync(CACHE_DIR, { recursive: true });
}

${generateStrategyCode(strategy, spec, prefix)}

// ─── Token Lifecycle ─────────────────────────────────────────

let cachedToken: string | null = null;
let tokenExpiry: number = 0;

export async function getAuthHeaders(): Promise<Record<string, string>> {
  const now = Date.now();

  // Return cached token if still valid (5 min buffer)
  if (cachedToken && tokenExpiry > now + 300_000) {
    return buildHeaders(cachedToken);
  }

  // Try to get a valid token
  const token = await getValidToken();
  if (!token) {
    throw new Error('[auth] No valid authentication token available. Run: mcp-forge auth');
  }

  cachedToken = token;
  return buildHeaders(token);
}

function buildHeaders(token: string): Record<string, string> {
${generateHeaderBuilder(strategy, spec)}
}

export function clearAuth(): void {
  cachedToken = null;
  tokenExpiry = 0;
  try {
    execSync(\`security delete-generic-password -s "\${SERVICE_NAME}" -a "access_token" 2>/dev/null\`);
    execSync(\`security delete-generic-password -s "\${SERVICE_NAME}" -a "refresh_token" 2>/dev/null\`);
    execSync(\`security delete-generic-password -s "\${SERVICE_NAME}" -a "expires_at" 2>/dev/null\`);
  } catch { /* ignore */ }
  console.log('[auth] Credentials cleared.');
}
`;
}

function generateStrategyCode(strategy: AuthStrategy, spec: ApiSpec, prefix: string): string {
  switch (strategy) {
    case 'api_key':
      return `
// ─── API Key Auth ────────────────────────────────────────────

async function getValidToken(): Promise<string | null> {
  // 1. Check environment variable
  const envKey = process.env['${spec.authConfig.envVarName || `${prefix}_API_KEY`}'];
  if (envKey) return envKey;

  // 2. Check Keychain
  const saved = keychainGet('api_key');
  if (saved) return saved;

  console.error('[auth] No API key found. Set ${spec.authConfig.envVarName || `${prefix}_API_KEY`} or run: mcp-forge auth');
  return null;
}

export async function saveApiKey(key: string): Promise<void> {
  keychainSet('api_key', key);
  console.log('[auth] API key saved to Keychain.');
}
`;

    case 'bearer':
      return `
// ─── Bearer Token Auth ───────────────────────────────────────

async function getValidToken(): Promise<string | null> {
  // 1. Check environment variable
  const envToken = process.env['${spec.authConfig.envVarName || `${prefix}_TOKEN`}'];
  if (envToken) return envToken;

  // 2. Check Keychain
  const saved = keychainGet('access_token');
  const expiresStr = keychainGet('expires_at');
  if (saved && expiresStr) {
    const expires = parseInt(expiresStr, 10);
    if (Date.now() < expires - 300_000) {
      tokenExpiry = expires;
      return saved;
    }
  }

  // 3. Try refresh
  const refreshed = await refreshToken();
  if (refreshed) return refreshed;

  console.error('[auth] No valid token. Set ${spec.authConfig.envVarName || `${prefix}_TOKEN`} or run: mcp-forge auth');
  return null;
}

async function refreshToken(): Promise<string | null> {
  const refresh = keychainGet('refresh_token');
  if (!refresh) return null;
  // Implement refresh logic for your specific API
  console.error('[auth] Refresh token found but refresh endpoint not configured.');
  return null;
}
`;

    case 'oauth2':
      return `
// ─── OAuth2 Auth ─────────────────────────────────────────────

const TOKEN_URL = '${spec.authConfig.tokenUrl || `https://login.microsoftonline.com/\${process.env['${prefix}_TENANT_ID'] || 'common'}/oauth2/v2.0/token`}';

async function getValidToken(): Promise<string | null> {
  // 1. Check cached/stored token
  const saved = keychainGet('access_token');
  const expiresStr = keychainGet('expires_at');
  if (saved && expiresStr) {
    const expires = parseInt(expiresStr, 10);
    if (Date.now() < expires - 300_000) {
      tokenExpiry = expires;
      return saved;
    }
  }

  // 2. Try refresh token
  const refreshed = await refreshToken();
  if (refreshed) return refreshed;

  // 3. Try client credentials
  const clientId = process.env['${prefix}_CLIENT_ID'];
  const clientSecret = process.env['${prefix}_CLIENT_SECRET'];
  if (clientId && clientSecret) {
    return await clientCredentialsGrant(clientId, clientSecret);
  }

  console.error('[auth] No valid OAuth2 credentials. Set ${prefix}_CLIENT_ID and ${prefix}_CLIENT_SECRET.');
  return null;
}

async function refreshToken(): Promise<string | null> {
  const refresh = keychainGet('refresh_token');
  const clientId = process.env['${prefix}_CLIENT_ID'];
  if (!refresh || !clientId) return null;

  try {
    const resp = await fetch(TOKEN_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        grant_type: 'refresh_token',
        client_id: clientId,
        refresh_token: refresh,
        scope: '${spec.authConfig.scopes?.join(' ') || '.default'}',
      }),
    });
    const data: any = await resp.json();
    if (data.access_token) {
      const expiresAt = Date.now() + (data.expires_in || 3600) * 1000;
      keychainSet('access_token', data.access_token);
      keychainSet('expires_at', expiresAt.toString());
      if (data.refresh_token) keychainSet('refresh_token', data.refresh_token);
      tokenExpiry = expiresAt;
      return data.access_token;
    }
  } catch (err) {
    console.error('[auth] Token refresh failed:', err);
  }
  return null;
}

async function clientCredentialsGrant(clientId: string, clientSecret: string): Promise<string | null> {
  try {
    const resp = await fetch(TOKEN_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        grant_type: 'client_credentials',
        client_id: clientId,
        client_secret: clientSecret,
        scope: '${spec.authConfig.scopes?.join(' ') || '.default'}',
      }),
    });
    const data: any = await resp.json();
    if (data.access_token) {
      const expiresAt = Date.now() + (data.expires_in || 3600) * 1000;
      keychainSet('access_token', data.access_token);
      keychainSet('expires_at', expiresAt.toString());
      tokenExpiry = expiresAt;
      return data.access_token;
    }
  } catch (err) {
    console.error('[auth] Client credentials grant failed:', err);
  }
  return null;
}
`;

    case 'sso_browser':
      return `
// ─── SSO Browser Auth ────────────────────────────────────────

async function getValidToken(): Promise<string | null> {
  // 1. Check for cookie cache
  ensureCacheDir();
  const cookiePath = join(CACHE_DIR, 'cookies.json');
  if (existsSync(cookiePath)) {
    try {
      const cookies = JSON.parse(readFileSync(cookiePath, 'utf-8'));
      const authCookie = cookies.find((c: any) =>
        c.name === 'JSESSIONID' || c.name === 'glide_user_route' || c.name.includes('session')
      );
      if (authCookie) {
        // Check if cookie is not expired
        if (!authCookie.expires || authCookie.expires === -1 || authCookie.expires * 1000 > Date.now()) {
          return JSON.stringify(cookies);
        }
      }
    } catch { /* corrupt cache, fall through */ }
  }

  // 2. Check Keychain for stored cookies
  const storedCookies = keychainGet('cookies');
  if (storedCookies) {
    try {
      const cookies = JSON.parse(storedCookies);
      writeFileSync(cookiePath, storedCookies);
      return storedCookies;
    } catch { /* fall through */ }
  }

  // 3. Need browser login
  console.error('[auth] No valid SSO session. Run: mcp-forge auth --browser');
  return null;
}

export async function browserLogin(loginUrl?: string): Promise<boolean> {
  const url = loginUrl || '${spec.authConfig.loginUrl || spec.baseUrl}';
  try {
    const { chromium } = await import('playwright');
    const browser = await chromium.launch({ headless: false });
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto(url);

    console.log('[auth] Browser opened. Please complete SSO login...');
    console.log('[auth] The browser will close automatically when authentication is detected.');

    // Wait for auth-related cookies to appear
    let authenticated = false;
    for (let i = 0; i < 120; i++) {
      await new Promise(r => setTimeout(r, 2000));
      const cookies = await context.cookies();
      const hasAuth = cookies.some(c =>
        c.name === 'JSESSIONID' || c.name.includes('session') || c.name.includes('token')
      );
      if (hasAuth && cookies.length > 3) {
        // Save cookies
        const cookieJson = JSON.stringify(cookies);
        keychainSet('cookies', cookieJson);
        ensureCacheDir();
        writeFileSync(join(CACHE_DIR, 'cookies.json'), cookieJson);
        authenticated = true;
        console.log(\`[auth] SSO login successful! Captured \${cookies.length} cookies.\`);
        break;
      }
    }

    await browser.close();
    return authenticated;
  } catch (err) {
    console.error('[auth] Browser login failed:', err);
    return false;
  }
}
`;

    case 'basic':
      return `
// ─── Basic Auth ──────────────────────────────────────────────

async function getValidToken(): Promise<string | null> {
  const user = process.env['${prefix}_USERNAME'] || keychainGet('username');
  const pass = process.env['${prefix}_PASSWORD'] || keychainGet('password');
  if (user && pass) {
    return Buffer.from(\`\${user}:\${pass}\`).toString('base64');
  }
  console.error('[auth] No credentials. Set ${prefix}_USERNAME and ${prefix}_PASSWORD.');
  return null;
}
`;

    case 'har_capture':
      return `
// ─── HAR Capture Auth ────────────────────────────────────────

async function getValidToken(): Promise<string | null> {
  // Check for stored auth headers from HAR
  const authHeader = keychainGet('auth_header');
  if (authHeader) return authHeader;

  const cookies = keychainGet('cookies');
  if (cookies) return cookies;

  console.error('[auth] No captured auth. Import a HAR file with: mcp-forge auth --har <file>');
  return null;
}
`;

    default:
      return `
// ─── No Auth ─────────────────────────────────────────────────

async function getValidToken(): Promise<string | null> {
  return 'no-auth-required';
}
`;
  }
}

function generateHeaderBuilder(strategy: AuthStrategy, spec: ApiSpec): string {
  switch (strategy) {
    case 'api_key':
      if (spec.authConfig.headerName) {
        return `  return { '${spec.authConfig.headerName}': token };`;
      }
      return `  return { 'X-API-Key': token };`;
    case 'bearer':
    case 'oauth2':
      return `  return { 'Authorization': \`Bearer \${token}\` };`;
    case 'basic':
      return `  return { 'Authorization': \`Basic \${token}\` };`;
    case 'sso_browser':
    case 'har_capture':
      return `  // SSO uses cookies, not headers
  try {
    const cookies = JSON.parse(token);
    const cookieStr = cookies.map((c: any) => \`\${c.name}=\${c.value}\`).join('; ');
    return { 'Cookie': cookieStr };
  } catch {
    return { 'Cookie': token };
  }`;
    default:
      return `  return {};`;
  }
}
